services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Avoid overriding node_modules
    environment:
      - NODE_ENV=development
    command: "npm run dev"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/src:/src/src
      - ./backend/node_modules:/src/node_modules
      - ./backend/nodemon.json:/src/nodemon.json
    ports:
      - "4000:4000"
    expose:
      - "4000"
    command: npm run dev
